// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: api/luckydraw_setting.proto

package setting

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Distribution struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Records []*Distribution_Record `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
}

func (x *Distribution) Reset() {
	*x = Distribution{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_luckydraw_setting_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Distribution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Distribution) ProtoMessage() {}

func (x *Distribution) ProtoReflect() protoreflect.Message {
	mi := &file_api_luckydraw_setting_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Distribution.ProtoReflect.Descriptor instead.
func (*Distribution) Descriptor() ([]byte, []int) {
	return file_api_luckydraw_setting_proto_rawDescGZIP(), []int{0}
}

func (x *Distribution) GetRecords() []*Distribution_Record {
	if x != nil {
		return x.Records
	}
	return nil
}

type Payrate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Records []*Payrate_Record `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
}

func (x *Payrate) Reset() {
	*x = Payrate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_luckydraw_setting_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Payrate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payrate) ProtoMessage() {}

func (x *Payrate) ProtoReflect() protoreflect.Message {
	mi := &file_api_luckydraw_setting_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payrate.ProtoReflect.Descriptor instead.
func (*Payrate) Descriptor() ([]byte, []int) {
	return file_api_luckydraw_setting_proto_rawDescGZIP(), []int{1}
}

func (x *Payrate) GetRecords() []*Payrate_Record {
	if x != nil {
		return x.Records
	}
	return nil
}

type Distribution_Record struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Symbol string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Reel_1 uint32 `protobuf:"varint,2,opt,name=reel_1,json=reel1,proto3" json:"reel_1,omitempty"`
	Reel_2 uint32 `protobuf:"varint,3,opt,name=reel_2,json=reel2,proto3" json:"reel_2,omitempty"`
	Reel_3 uint32 `protobuf:"varint,4,opt,name=reel_3,json=reel3,proto3" json:"reel_3,omitempty"`
}

func (x *Distribution_Record) Reset() {
	*x = Distribution_Record{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_luckydraw_setting_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Distribution_Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Distribution_Record) ProtoMessage() {}

func (x *Distribution_Record) ProtoReflect() protoreflect.Message {
	mi := &file_api_luckydraw_setting_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Distribution_Record.ProtoReflect.Descriptor instead.
func (*Distribution_Record) Descriptor() ([]byte, []int) {
	return file_api_luckydraw_setting_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Distribution_Record) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Distribution_Record) GetReel_1() uint32 {
	if x != nil {
		return x.Reel_1
	}
	return 0
}

func (x *Distribution_Record) GetReel_2() uint32 {
	if x != nil {
		return x.Reel_2
	}
	return 0
}

func (x *Distribution_Record) GetReel_3() uint32 {
	if x != nil {
		return x.Reel_3
	}
	return 0
}

type Payrate_Record struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Symbol   string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Multiply int64  `protobuf:"varint,2,opt,name=multiply,proto3" json:"multiply,omitempty"`
}

func (x *Payrate_Record) Reset() {
	*x = Payrate_Record{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_luckydraw_setting_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Payrate_Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payrate_Record) ProtoMessage() {}

func (x *Payrate_Record) ProtoReflect() protoreflect.Message {
	mi := &file_api_luckydraw_setting_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payrate_Record.ProtoReflect.Descriptor instead.
func (*Payrate_Record) Descriptor() ([]byte, []int) {
	return file_api_luckydraw_setting_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Payrate_Record) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Payrate_Record) GetMultiply() int64 {
	if x != nil {
		return x.Multiply
	}
	return 0
}

var File_api_luckydraw_setting_proto protoreflect.FileDescriptor

var file_api_luckydraw_setting_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x61, 0x70, 0x69, 0x2f, 0x6c, 0x75, 0x63, 0x6b, 0x79, 0x64, 0x72, 0x61, 0x77, 0x5f,
	0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x6c,
	0x75, 0x63, 0x6b, 0x79, 0x64, 0x72, 0x61, 0x77, 0x2e, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67,
	0x2e, 0x76, 0x31, 0x22, 0xba, 0x01, 0x0a, 0x0c, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x43, 0x0a, 0x07, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x6c, 0x75, 0x63, 0x6b, 0x79, 0x64, 0x72, 0x61,
	0x77, 0x2e, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x69, 0x73,
	0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x52, 0x07, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x1a, 0x65, 0x0a, 0x06, 0x52, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x15, 0x0a, 0x06, 0x72,
	0x65, 0x65, 0x6c, 0x5f, 0x31, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x72, 0x65, 0x65,
	0x6c, 0x31, 0x12, 0x15, 0x0a, 0x06, 0x72, 0x65, 0x65, 0x6c, 0x5f, 0x32, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x05, 0x72, 0x65, 0x65, 0x6c, 0x32, 0x12, 0x15, 0x0a, 0x06, 0x72, 0x65, 0x65,
	0x6c, 0x5f, 0x33, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x72, 0x65, 0x65, 0x6c, 0x33,
	0x22, 0x87, 0x01, 0x0a, 0x07, 0x50, 0x61, 0x79, 0x72, 0x61, 0x74, 0x65, 0x12, 0x3e, 0x0a, 0x07,
	0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x24, 0x2e,
	0x6c, 0x75, 0x63, 0x6b, 0x79, 0x64, 0x72, 0x61, 0x77, 0x2e, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e,
	0x67, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x79, 0x72, 0x61, 0x74, 0x65, 0x2e, 0x52, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x52, 0x07, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x1a, 0x3c, 0x0a, 0x06,
	0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x1a,
	0x0a, 0x08, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x08, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x79, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x69, 0x6e, 0x6b, 0x6e, 0x74, 0x61,
	0x2f, 0x6c, 0x75, 0x63, 0x6b, 0x79, 0x64, 0x72, 0x61, 0x77, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76,
	0x31, 0x2f, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x3b, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e,
	0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_luckydraw_setting_proto_rawDescOnce sync.Once
	file_api_luckydraw_setting_proto_rawDescData = file_api_luckydraw_setting_proto_rawDesc
)

func file_api_luckydraw_setting_proto_rawDescGZIP() []byte {
	file_api_luckydraw_setting_proto_rawDescOnce.Do(func() {
		file_api_luckydraw_setting_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_luckydraw_setting_proto_rawDescData)
	})
	return file_api_luckydraw_setting_proto_rawDescData
}

var file_api_luckydraw_setting_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_luckydraw_setting_proto_goTypes = []interface{}{
	(*Distribution)(nil),        // 0: luckydraw.setting.v1.Distribution
	(*Payrate)(nil),             // 1: luckydraw.setting.v1.Payrate
	(*Distribution_Record)(nil), // 2: luckydraw.setting.v1.Distribution.Record
	(*Payrate_Record)(nil),      // 3: luckydraw.setting.v1.Payrate.Record
}
var file_api_luckydraw_setting_proto_depIdxs = []int32{
	2, // 0: luckydraw.setting.v1.Distribution.records:type_name -> luckydraw.setting.v1.Distribution.Record
	3, // 1: luckydraw.setting.v1.Payrate.records:type_name -> luckydraw.setting.v1.Payrate.Record
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_luckydraw_setting_proto_init() }
func file_api_luckydraw_setting_proto_init() {
	if File_api_luckydraw_setting_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_luckydraw_setting_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Distribution); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_luckydraw_setting_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Payrate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_luckydraw_setting_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Distribution_Record); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_luckydraw_setting_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Payrate_Record); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_luckydraw_setting_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_luckydraw_setting_proto_goTypes,
		DependencyIndexes: file_api_luckydraw_setting_proto_depIdxs,
		MessageInfos:      file_api_luckydraw_setting_proto_msgTypes,
	}.Build()
	File_api_luckydraw_setting_proto = out.File
	file_api_luckydraw_setting_proto_rawDesc = nil
	file_api_luckydraw_setting_proto_goTypes = nil
	file_api_luckydraw_setting_proto_depIdxs = nil
}
